repos:
  # --- run Black that’s already in your .venv ---
  -   repo: local
      hooks:
        - id: black
          name: black
          entry: python -m black
          language: system     # ← no virtualenv
          types: [python]

  # --- run Flake8 from your .venv ---
        - id: flake8
          name: flake8
          entry: python -m flake8
          language: system
          types: [python]
