name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Pillow source build safety (harmless if Pillow absent)
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libjpeg-dev zlib1g-dev

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install runtime dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install dev dependencies
      run: |
        pip install -r requirements-dev.txt

    - name: Lint
      run: flake8 .

    - name: Run tests
      run: pytest
