name: CI

# Run on every push or pull request to main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. (Optional) install system deps so Pillow can build if needed
      - name: Install system dependencies for Pillow
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libjpeg-dev zlib1g-dev

      # 3. Set up Python (pin to 3.11 for best wheel support)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 4. Install your runtime + dev dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # If you followed the suggestion and created requirements-dev.txt:
          pip install -r requirements-dev.txt

      # 5. Lint your code
      - name: Lint with flake8
        run: flake8 .

      # 6. Run your pytest suite
      - name: Run unit tests
        run: pytest
